sonar.organization=akshay-sakharwade
sonar.projectKey=akshay-sakharwade_three-tier-k8s-devsecops-gitops-observability-self-healing
sonar.projectName=three-tier-k8s-devsecops
sonar.sources=frontend,backend
sonar.sourceEncoding=UT-8
